
package br.gov.iphan.sisgep.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ConsultaSIAPE", targetNamespace = "http://servico.wssiapenet")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ConsultaSIAPE {


    /**
     * 
     * @param parmExistPag
     * @param senha
     * @param codOrgao
     * @param parmTipoVinculo
     * @param siglaSistema
     * @param cpf
     * @param nomeSistema
     * @return
     *     returns br.gov.iphan.sisgep.ws.DadosDocumentacao
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(name = "out", partName = "out")
    public DadosDocumentacao consultaDadosDocumentacao(
        @WebParam(name = "siglaSistema", partName = "siglaSistema")
        String siglaSistema,
        @WebParam(name = "nomeSistema", partName = "nomeSistema")
        String nomeSistema,
        @WebParam(name = "senha", partName = "senha")
        String senha,
        @WebParam(name = "cpf", partName = "cpf")
        String cpf,
        @WebParam(name = "codOrgao", partName = "codOrgao")
        String codOrgao,
        @WebParam(name = "parmExistPag", partName = "parmExistPag")
        String parmExistPag,
        @WebParam(name = "parmTipoVinculo", partName = "parmTipoVinculo")
        String parmTipoVinculo)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param senha
     * @param codOrgao
     * @param siglaSistema
     * @param cpf
     * @param nomeSistema
     * @param codUorg
     * @return
     *     returns br.gov.iphan.sisgep.ws.ArrayOfServidor
     */
    @WebMethod
    @WebResult(name = "out", partName = "out")
    public ArrayOfServidor listaServidores(
        @WebParam(name = "siglaSistema", partName = "siglaSistema")
        String siglaSistema,
        @WebParam(name = "nomeSistema", partName = "nomeSistema")
        String nomeSistema,
        @WebParam(name = "senha", partName = "senha")
        String senha,
        @WebParam(name = "cpf", partName = "cpf")
        String cpf,
        @WebParam(name = "codOrgao", partName = "codOrgao")
        String codOrgao,
        @WebParam(name = "codUorg", partName = "codUorg")
        String codUorg);

    /**
     * 
     * @param parmExistPag
     * @param senha
     * @param codOrgao
     * @param parmTipoVinculo
     * @param siglaSistema
     * @param cpf
     * @param nomeSistema
     * @return
     *     returns br.gov.iphan.sisgep.ws.ArrayDadosFinanceiros
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(name = "out", partName = "out")
    public ArrayDadosFinanceiros consultaDadosFinanceiros(
        @WebParam(name = "siglaSistema", partName = "siglaSistema")
        String siglaSistema,
        @WebParam(name = "nomeSistema", partName = "nomeSistema")
        String nomeSistema,
        @WebParam(name = "senha", partName = "senha")
        String senha,
        @WebParam(name = "cpf", partName = "cpf")
        String cpf,
        @WebParam(name = "codOrgao", partName = "codOrgao")
        String codOrgao,
        @WebParam(name = "parmExistPag", partName = "parmExistPag")
        String parmExistPag,
        @WebParam(name = "parmTipoVinculo", partName = "parmTipoVinculo")
        String parmTipoVinculo)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parmExistPag
     * @param senha
     * @param codOrgao
     * @param parmTipoVinculo
     * @param siglaSistema
     * @param cpf
     * @param nomeSistema
     * @return
     *     returns br.gov.iphan.sisgep.ws.ArrayDadosSICAJ
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(name = "out", partName = "out")
    public ArrayDadosSICAJ consultaDadosSICAJ(
        @WebParam(name = "siglaSistema", partName = "siglaSistema")
        String siglaSistema,
        @WebParam(name = "nomeSistema", partName = "nomeSistema")
        String nomeSistema,
        @WebParam(name = "senha", partName = "senha")
        String senha,
        @WebParam(name = "cpf", partName = "cpf")
        String cpf,
        @WebParam(name = "codOrgao", partName = "codOrgao")
        String codOrgao,
        @WebParam(name = "parmExistPag", partName = "parmExistPag")
        String parmExistPag,
        @WebParam(name = "parmTipoVinculo", partName = "parmTipoVinculo")
        String parmTipoVinculo)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parmExistPag
     * @param senha
     * @param codOrgao
     * @param parmTipoVinculo
     * @param siglaSistema
     * @param cpf
     * @param nomeSistema
     * @return
     *     returns br.gov.iphan.sisgep.ws.ArrayDadosFuncionais
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(name = "out", partName = "out")
    public ArrayDadosFuncionais consultaDadosFuncionais(
        @WebParam(name = "siglaSistema", partName = "siglaSistema")
        String siglaSistema,
        @WebParam(name = "nomeSistema", partName = "nomeSistema")
        String nomeSistema,
        @WebParam(name = "senha", partName = "senha")
        String senha,
        @WebParam(name = "cpf", partName = "cpf")
        String cpf,
        @WebParam(name = "codOrgao", partName = "codOrgao")
        String codOrgao,
        @WebParam(name = "parmExistPag", partName = "parmExistPag")
        String parmExistPag,
        @WebParam(name = "parmTipoVinculo", partName = "parmTipoVinculo")
        String parmTipoVinculo)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param senha
     * @param cpf
     * @param siglaSistema
     * @param nomeSistema
     * @param cpfPensionista
     * @return
     *     returns br.gov.iphan.sisgep.ws.Pensionista
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(name = "out", partName = "out")
    public Pensionista getPensionista(
        @WebParam(name = "cpfPensionista", partName = "cpfPensionista")
        String cpfPensionista,
        @WebParam(name = "cpf", partName = "cpf")
        String cpf,
        @WebParam(name = "siglaSistema", partName = "siglaSistema")
        String siglaSistema,
        @WebParam(name = "nomeSistema", partName = "nomeSistema")
        String nomeSistema,
        @WebParam(name = "senha", partName = "senha")
        String senha)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parmExistPag
     * @param senha
     * @param codOrgao
     * @param parmTipoVinculo
     * @param siglaSistema
     * @param cpf
     * @param nomeSistema
     * @return
     *     returns br.gov.iphan.sisgep.ws.DadosEscolares
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(name = "out", partName = "out")
    public DadosEscolares consultaDadosEscolares(
        @WebParam(name = "siglaSistema", partName = "siglaSistema")
        String siglaSistema,
        @WebParam(name = "nomeSistema", partName = "nomeSistema")
        String nomeSistema,
        @WebParam(name = "senha", partName = "senha")
        String senha,
        @WebParam(name = "cpf", partName = "cpf")
        String cpf,
        @WebParam(name = "codOrgao", partName = "codOrgao")
        String codOrgao,
        @WebParam(name = "parmExistPag", partName = "parmExistPag")
        String parmExistPag,
        @WebParam(name = "parmTipoVinculo", partName = "parmTipoVinculo")
        String parmTipoVinculo)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parmExistPag
     * @param senha
     * @param codOrgao
     * @param parmTipoVinculo
     * @param siglaSistema
     * @param cpf
     * @param nomeSistema
     * @return
     *     returns br.gov.iphan.sisgep.ws.ArrayDadosBancarios
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(name = "out", partName = "out")
    public ArrayDadosBancarios consultaDadosBancarios(
        @WebParam(name = "siglaSistema", partName = "siglaSistema")
        String siglaSistema,
        @WebParam(name = "nomeSistema", partName = "nomeSistema")
        String nomeSistema,
        @WebParam(name = "senha", partName = "senha")
        String senha,
        @WebParam(name = "cpf", partName = "cpf")
        String cpf,
        @WebParam(name = "codOrgao", partName = "codOrgao")
        String codOrgao,
        @WebParam(name = "parmExistPag", partName = "parmExistPag")
        String parmExistPag,
        @WebParam(name = "parmTipoVinculo", partName = "parmTipoVinculo")
        String parmTipoVinculo)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parmExistPag
     * @param senha
     * @param codOrgao
     * @param parmTipoVinculo
     * @param siglaSistema
     * @param cpf
     * @param nomeSistema
     * @return
     *     returns br.gov.iphan.sisgep.ws.DadosEnderecoResidencial
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(name = "out", partName = "out")
    public DadosEnderecoResidencial consultaDadosEnderecoResidencial(
        @WebParam(name = "siglaSistema", partName = "siglaSistema")
        String siglaSistema,
        @WebParam(name = "nomeSistema", partName = "nomeSistema")
        String nomeSistema,
        @WebParam(name = "senha", partName = "senha")
        String senha,
        @WebParam(name = "cpf", partName = "cpf")
        String cpf,
        @WebParam(name = "codOrgao", partName = "codOrgao")
        String codOrgao,
        @WebParam(name = "parmExistPag", partName = "parmExistPag")
        String parmExistPag,
        @WebParam(name = "parmTipoVinculo", partName = "parmTipoVinculo")
        String parmTipoVinculo)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parmExistPag
     * @param senha
     * @param codOrgao
     * @param parmTipoVinculo
     * @param siglaSistema
     * @param cpf
     * @param nomeSistema
     * @return
     *     returns br.gov.iphan.sisgep.ws.ArrayDadosAfastamento
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(name = "out", partName = "out")
    public ArrayDadosAfastamento consultaDadosAfastamento(
        @WebParam(name = "siglaSistema", partName = "siglaSistema")
        String siglaSistema,
        @WebParam(name = "nomeSistema", partName = "nomeSistema")
        String nomeSistema,
        @WebParam(name = "senha", partName = "senha")
        String senha,
        @WebParam(name = "cpf", partName = "cpf")
        String cpf,
        @WebParam(name = "codOrgao", partName = "codOrgao")
        String codOrgao,
        @WebParam(name = "parmExistPag", partName = "parmExistPag")
        String parmExistPag,
        @WebParam(name = "parmTipoVinculo", partName = "parmTipoVinculo")
        String parmTipoVinculo)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parmExistPag
     * @param senha
     * @param codOrgao
     * @param parmTipoVinculo
     * @param siglaSistema
     * @param cpf
     * @param nomeSistema
     * @return
     *     returns br.gov.iphan.sisgep.ws.ArrayDadosRepresentanteLegal
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(name = "out", partName = "out")
    public ArrayDadosRepresentanteLegal consultaDadosRepresentanteLegal(
        @WebParam(name = "siglaSistema", partName = "siglaSistema")
        String siglaSistema,
        @WebParam(name = "nomeSistema", partName = "nomeSistema")
        String nomeSistema,
        @WebParam(name = "senha", partName = "senha")
        String senha,
        @WebParam(name = "cpf", partName = "cpf")
        String cpf,
        @WebParam(name = "codOrgao", partName = "codOrgao")
        String codOrgao,
        @WebParam(name = "parmExistPag", partName = "parmExistPag")
        String parmExistPag,
        @WebParam(name = "parmTipoVinculo", partName = "parmTipoVinculo")
        String parmTipoVinculo)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parmExistPag
     * @param senha
     * @param codOrgao
     * @param parmTipoVinculo
     * @param siglaSistema
     * @param cpf
     * @param nomeSistema
     * @return
     *     returns br.gov.iphan.sisgep.ws.DadosCurriculo
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(name = "out", partName = "out")
    public DadosCurriculo consultaDadosCurriculo(
        @WebParam(name = "siglaSistema", partName = "siglaSistema")
        String siglaSistema,
        @WebParam(name = "nomeSistema", partName = "nomeSistema")
        String nomeSistema,
        @WebParam(name = "senha", partName = "senha")
        String senha,
        @WebParam(name = "cpf", partName = "cpf")
        String cpf,
        @WebParam(name = "codOrgao", partName = "codOrgao")
        String codOrgao,
        @WebParam(name = "parmExistPag", partName = "parmExistPag")
        String parmExistPag,
        @WebParam(name = "parmTipoVinculo", partName = "parmTipoVinculo")
        String parmTipoVinculo)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parmExistPag
     * @param senha
     * @param codOrgao
     * @param parmTipoVinculo
     * @param siglaSistema
     * @param cpf
     * @param nomeSistema
     * @return
     *     returns br.gov.iphan.sisgep.ws.ArrayDadosUorg
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(name = "out", partName = "out")
    public ArrayDadosUorg consultaDadosUorg(
        @WebParam(name = "siglaSistema", partName = "siglaSistema")
        String siglaSistema,
        @WebParam(name = "nomeSistema", partName = "nomeSistema")
        String nomeSistema,
        @WebParam(name = "senha", partName = "senha")
        String senha,
        @WebParam(name = "cpf", partName = "cpf")
        String cpf,
        @WebParam(name = "codOrgao", partName = "codOrgao")
        String codOrgao,
        @WebParam(name = "parmExistPag", partName = "parmExistPag")
        String parmExistPag,
        @WebParam(name = "parmTipoVinculo", partName = "parmTipoVinculo")
        String parmTipoVinculo)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param senha
     * @param codOrgao
     * @param siglaSistema
     * @param cpf
     * @param nomeSistema
     * @return
     *     returns br.gov.iphan.sisgep.ws.TotalVagasOrgao
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(name = "out", partName = "out")
    public TotalVagasOrgao consultaTotalizadorVagasOrgao(
        @WebParam(name = "siglaSistema", partName = "siglaSistema")
        String siglaSistema,
        @WebParam(name = "nomeSistema", partName = "nomeSistema")
        String nomeSistema,
        @WebParam(name = "senha", partName = "senha")
        String senha,
        @WebParam(name = "cpf", partName = "cpf")
        String cpf,
        @WebParam(name = "codOrgao", partName = "codOrgao")
        String codOrgao)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param senha
     * @param codOrgao
     * @param siglaSistema
     * @param cpf
     * @param nomeSistema
     * @param codUorg
     * @return
     *     returns br.gov.iphan.sisgep.ws.UorgDados
     */
    @WebMethod
    @WebResult(name = "out", partName = "out")
    public UorgDados dadosUorg(
        @WebParam(name = "siglaSistema", partName = "siglaSistema")
        String siglaSistema,
        @WebParam(name = "nomeSistema", partName = "nomeSistema")
        String nomeSistema,
        @WebParam(name = "senha", partName = "senha")
        String senha,
        @WebParam(name = "cpf", partName = "cpf")
        String cpf,
        @WebParam(name = "codOrgao", partName = "codOrgao")
        String codOrgao,
        @WebParam(name = "codUorg", partName = "codUorg")
        String codUorg);

    /**
     * 
     * @param parmExistPag
     * @param senha
     * @param codOrgao
     * @param parmTipoVinculo
     * @param siglaSistema
     * @param cpf
     * @param nomeSistema
     * @return
     *     returns br.gov.iphan.sisgep.ws.ArrayDadosDependentes
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(name = "out", partName = "out")
    public ArrayDadosDependentes consultaDadosDependentes(
        @WebParam(name = "siglaSistema", partName = "siglaSistema")
        String siglaSistema,
        @WebParam(name = "nomeSistema", partName = "nomeSistema")
        String nomeSistema,
        @WebParam(name = "senha", partName = "senha")
        String senha,
        @WebParam(name = "cpf", partName = "cpf")
        String cpf,
        @WebParam(name = "codOrgao", partName = "codOrgao")
        String codOrgao,
        @WebParam(name = "parmExistPag", partName = "parmExistPag")
        String parmExistPag,
        @WebParam(name = "parmTipoVinculo", partName = "parmTipoVinculo")
        String parmTipoVinculo)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parmExistPag
     * @param senha
     * @param codOrgao
     * @param parmTipoVinculo
     * @param siglaSistema
     * @param cpf
     * @param nomeSistema
     * @return
     *     returns br.gov.iphan.sisgep.ws.ArrayDadosPA
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(name = "out", partName = "out")
    public ArrayDadosPA consultaDadosPA(
        @WebParam(name = "siglaSistema", partName = "siglaSistema")
        String siglaSistema,
        @WebParam(name = "nomeSistema", partName = "nomeSistema")
        String nomeSistema,
        @WebParam(name = "senha", partName = "senha")
        String senha,
        @WebParam(name = "cpf", partName = "cpf")
        String cpf,
        @WebParam(name = "codOrgao", partName = "codOrgao")
        String codOrgao,
        @WebParam(name = "parmExistPag", partName = "parmExistPag")
        String parmExistPag,
        @WebParam(name = "parmTipoVinculo", partName = "parmTipoVinculo")
        String parmTipoVinculo)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param senha
     * @param codOrgao
     * @param siglaSistema
     * @param cpf
     * @param nomeSistema
     * @param codUorg
     * @return
     *     returns br.gov.iphan.sisgep.ws.ArrayOfUorg
     */
    @WebMethod
    @WebResult(name = "out", partName = "out")
    public ArrayOfUorg listaUorgs(
        @WebParam(name = "siglaSistema", partName = "siglaSistema")
        String siglaSistema,
        @WebParam(name = "nomeSistema", partName = "nomeSistema")
        String nomeSistema,
        @WebParam(name = "senha", partName = "senha")
        String senha,
        @WebParam(name = "cpf", partName = "cpf")
        String cpf,
        @WebParam(name = "codOrgao", partName = "codOrgao")
        String codOrgao,
        @WebParam(name = "codUorg", partName = "codUorg")
        String codUorg);

    /**
     * 
     * @param parmExistPag
     * @param senha
     * @param codOrgao
     * @param parmTipoVinculo
     * @param siglaSistema
     * @param cpf
     * @param nomeSistema
     * @return
     *     returns br.gov.iphan.sisgep.ws.DadosPessoais
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(name = "out", partName = "out")
    public DadosPessoais consultaDadosPessoais(
        @WebParam(name = "siglaSistema", partName = "siglaSistema")
        String siglaSistema,
        @WebParam(name = "nomeSistema", partName = "nomeSistema")
        String nomeSistema,
        @WebParam(name = "senha", partName = "senha")
        String senha,
        @WebParam(name = "cpf", partName = "cpf")
        String cpf,
        @WebParam(name = "codOrgao", partName = "codOrgao")
        String codOrgao,
        @WebParam(name = "parmExistPag", partName = "parmExistPag")
        String parmExistPag,
        @WebParam(name = "parmTipoVinculo", partName = "parmTipoVinculo")
        String parmTipoVinculo)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parmExistPag
     * @param senha
     * @param codOrgao
     * @param parmTipoVinculo
     * @param siglaSistema
     * @param cpf
     * @param nomeSistema
     * @return
     *     returns br.gov.iphan.sisgep.ws.ArrayPensaoRecebida
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(name = "out", partName = "out")
    public ArrayPensaoRecebida consultaPensaoRecebida(
        @WebParam(name = "siglaSistema", partName = "siglaSistema")
        String siglaSistema,
        @WebParam(name = "nomeSistema", partName = "nomeSistema")
        String nomeSistema,
        @WebParam(name = "senha", partName = "senha")
        String senha,
        @WebParam(name = "cpf", partName = "cpf")
        String cpf,
        @WebParam(name = "codOrgao", partName = "codOrgao")
        String codOrgao,
        @WebParam(name = "parmExistPag", partName = "parmExistPag")
        String parmExistPag,
        @WebParam(name = "parmTipoVinculo", partName = "parmTipoVinculo")
        String parmTipoVinculo)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param siglaSistema
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", partName = "out")
    public String obterVersao(
        @WebParam(name = "siglaSistema", partName = "siglaSistema")
        String siglaSistema);

    /**
     * 
     * @param parmExistPag
     * @param senha
     * @param codOrgao
     * @param parmTipoVinculo
     * @param siglaSistema
     * @param cpf
     * @param nomeSistema
     * @return
     *     returns br.gov.iphan.sisgep.ws.ArrayPensoesInstituidas
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(name = "out", partName = "out")
    public ArrayPensoesInstituidas consultaPensoesInstituidas(
        @WebParam(name = "siglaSistema", partName = "siglaSistema")
        String siglaSistema,
        @WebParam(name = "nomeSistema", partName = "nomeSistema")
        String nomeSistema,
        @WebParam(name = "senha", partName = "senha")
        String senha,
        @WebParam(name = "cpf", partName = "cpf")
        String cpf,
        @WebParam(name = "codOrgao", partName = "codOrgao")
        String codOrgao,
        @WebParam(name = "parmExistPag", partName = "parmExistPag")
        String parmExistPag,
        @WebParam(name = "parmTipoVinculo", partName = "parmTipoVinculo")
        String parmTipoVinculo)
        throws SQLException_Exception
    ;

}
